version: '3.9'

services:
  db:
    image: postgres:14
    command: postgres -p 49089
    restart: always
    env_file:
      - .env
    volumes:
      - ps_volume:/var/lib/postgresql/data

  backend:  
    build: ./backend
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - staticfiles:/backend/staticfiles
    depends_on:
      db:
        condition: service_started

  nginx:
    build: ./frontend
    restart: always
    volumes:
      - staticfiles:/staticfiles
    ports:
      - 80:80
    depends_on:
      backend:
        condition: service_started
  
  redis:
    restart: unless-stopped
    image: redis:7.0.5-alpine 
    expose:
        - 6379

  # celery:
  #   restart: unless-stopped
  #   build:
  #     ./celery
  #   depends_on:
  #       - redis
  #       - backend


volumes:
    ps_volume:
    staticfiles:
