version: '3.9'

services:
  db:
    image: postgres
    container_name: postgres_db
    command: postgres -p 49089
    restart: always
    environment:
     - POSTGRES_DB=automatic_tournament_system_db
     - POSTGRES_USER=admin
     - POSTGRES_PASSWORD=qe44iaEB6LZtpXb
    volumes:
      - db_volume:/var/lib/postgresql/data
    ports:
      - 49089:49089

  automatic_tournament_system:
    build: .
    container_name: automatic_tournament_system
    command: python /usr/src/automatic_tournament_system/manage.py runserver 0.0.0.0:49088
    volumes:
      - automatic_tournament_system_volume:/usr/src/automatic_tournament_system
    ports:
      - 49088:49088
    depends_on:
      - db

volumes:
    automatic_tournament_system_volume:
    db_volume: