# Generated by Django 4.1.2 on 2024-08-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_alter_tournament_prize'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='serial_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
