# Generated by Django 4.1.2 on 2024-09-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_round_serial_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='child',
        ),
        migrations.AddField(
            model_name='match',
            name='serial_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
