# Generated by Django 4.1.2 on 2025-03-08 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0023_tournamentnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentnotification',
            name='tournament',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='tournaments.tournament'),
        ),
    ]
